export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE';

export const FETCH_PRODUCT_ADD_SUCCESS = 'FETCH_PRODUCT_ADD_SUCCESS';
export const FETCH_PRODUCT_ADD_FAILURE = 'FETCH_PRODUCT_ADD_FAILURE';
export const FETCH_PRODUCT_ADD_REQUEST = 'FETCH_PRODUCT_ADD_REQUEST';

export const FETCH_PRODUCT_UPDATE_REQUEST = 'FETCH_PRODUCT_UPDATE_REQUEST';
export const FETCH_PRODUCT_UPDATE_SUCCESS = 'FETCH_PRODUCT_UPDATE_SUCCESS';
export const FETCH_PRODUCT_UPDATE_FAILURE = 'FETCH_PRODUCT_UPDATE_FAILURE';

export const FETCH_PRODUCT_DELETE_REQUEST = 'FETCH_PRODUCT_DELETE_REQUEST';
export const FETCH_PRODUCT_DELETE_SUCCESS = 'FETCH_PRODUCT_DELETE_SUCCESS';
export const FETCH_PRODUCT_DELETE_FAILURE = 'FETCH_PRODUCT_DELETE_FAILURE';
